#!/usr/bin/env python3

import sys

sep = ' '

for _ in range(int(sys.argv[1])):
    for i in range(100):
        for k in ['A', 'B', 'C']:
            print(f'value{sep}config{sep}{k}{sep}{i}')

    for i in range(100):
        for k in ['A', 'B', 'C']:
            print(f'device{sep}{k}{sep}{i}')
